name: potoo
namespace: sparrow
version: 0.0.10
author: Benoît Stahl
display_name: Potoo 🦉
description: ⚡️ This plugin adds more power to your engine 🔥
homepage: https://github.com/benasse/potoo
debian_depends:
  - python3-venv
